#!/usr/bin/env python

Import("env")

sources = Glob("*.cpp") + Glob("*/*.cpp") + Glob("*/*/*.cpp") + Glob("*/*/*/*.cpp") + Glob("*/*/*/*/*.cpp")
results = []

for src in sources:
    tgt = src.name.replace(".cpp", "")
    results += env.SharedObject(source = src, target = tgt)

Return ("results")